# Generated by Django 5.1 on 2024-09-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_rename_student_studentquestion_studentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
