# Generated by Django 5.1 on 2024-09-07 05:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersanwser',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
