# Generated by Django 5.1 on 2024-09-07 05:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_alter_teachersanwser_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestion',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
