# Generated by Django 5.1 on 2024-09-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_alter_dailystudentstats_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystudentstats',
            name='answered_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailystudentstats',
            name='asked_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailystudentstats',
            name='pending_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
