# Generated by Django 5.1 on 2024-09-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_alter_dailystudentstats_answered_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyStudentStats',
        ),
    ]
